---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Product
description: Product for sale
stability: prototype
strictProperties: true
type:
- object
properties:
  data:
    type:
    - array
    items:
      type:
      - object
      properties:
        product_identifier:
          description: unique identifier of product
          example: com.example.iap.coins.100
          readOnly: true
          pattern: "^[A-Za-z0-9_.]+$"
          type:
          - string
        localized_description:
          description: description of product
          example: description of product
          type:
          - string
        localized_title:
          description: title of product
          example: title of product
          type:
          - string
        price:
          description: price of product
          example: 100
          type:
          - integer
        price_locale:
          description: locale of product''s price
          example: en_US
          type:
          - string
        downloadable:
          description: downloadable flag of product
          example: false
          type:
          - boolean
        download_content_lengths:
          description: content lengths of downloadable product
          example: []
          type:
          - array
          items:
            type:
            - integer
        download_content_version:
          description: version of downloadable product
          example: 0
          type:
          - integer
        created_at:
          description: when product was created
          example: "2015-01-01T12:34:56.789Z"
          format: date-time
          type:
          - string
        updated_at:
          description: when product was updated
          example: "2015-01-01T12:34:56.789Z"
          format: date-time
          type:
          - string
      required:
      - product_identifier
      - localized_description
      - localized_title
      - price
      - price_locale
      - downloadable
      - created_at
      - updated_at
links:
- description: List existing products.
  href: "/products"
  method: GET
  rel: self
id: schemata/product
